name: Issue Close Require

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  close-issues:
    runs-on: ubuntu-latest
    steps:
      - name: need reproduce
        uses: actions-cool/issues-helper@v1.7
        with:
          actions: close-issues
          labels: Need Reproduce
          inactive-day: 14
          body: |
            Since the issue was labeled with `Need Reproduce`, but no response in 14 days. This issue will be closed. If you have any questions, you can comment and reply.

            由于该 issue 被标记为需要复现信息，却 14 天未收到回应。现关闭 issue，若有任何问题，可评论回复。
